import os
import google.generativeai as genai
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Configure the Gemini API key
api_key = os.getenv("GEMINI_API_KEY")
if api_key:
    genai.configure(api_key=api_key)

OUT_OF_SCOPE_MESSAGE = "I am sorry, this information seems to be out of scope."

# Define the System Instruction (Basic Guardrail)
SYSTEM_INSTRUCTION = f"""
You are the Power-Pulse Assistant, an AI expert in energy demand forecasting, power grids, and machine learning.
Your primary role is to assist users with questions about electricity, energy demand, power grids, and related topics of any sort.
Basic Guardrail: If a user asks a question that is entirely unrelated to energy, electricity, power grids, or machine learning, you must decline by replying EXACTLY with: "{OUT_OF_SCOPE_MESSAGE}".
Always be polite, professional, and concise. You may engage in basic pleasantries (like saying hello).
"""

def process_query(prompt: str, chat_history: list = None) -> str:
    """
    Process the user prompt using Google's Gemini API with conversation history.
    If the API key is not configured, falls back to a basic heuristic response.
    """
    # Fallback if the user hasn't set up the API key yet
    if not api_key:
        prompt_lower = prompt.lower()
        if prompt_lower.strip() in ["hi", "hello", "hey", "greetings"]:
            return "Hello. I am the Power-Pulse Assistant. How can I help you analyze the grid today? (Note: API Key not detected, running in limited mode)."
        return "I am currently running in limited mode because the GEMINI_API_KEY is not set in the .env file. Please add your key to enable full AI capabilities."

    try:
        # Initialize the Gemini Flash model (fast, generous free tier)
        model = genai.GenerativeModel(
            model_name="gemini-2.5-flash",
            system_instruction=SYSTEM_INSTRUCTION
        )
        
        # Format history for Gemini (roles must be 'user' or 'model')
        formatted_history = []
        if chat_history:
            for msg in chat_history:
                # Skip the initial system greeting as it wasn't generated by the model
                if msg["content"].startswith("SYSTEM INITIALIZED"):
                    continue
                role = "model" if msg["role"] == "assistant" else "user"
                formatted_history.append({"role": role, "parts": [msg["content"]]})
        
        # Start a chat session with the history
        chat = model.start_chat(history=formatted_history)
        
        # Send the new message
        response = chat.send_message(prompt)
        return response.text.strip()
        
    except Exception as e:
        return f"System Error: Unable to process query. ({str(e)})"
